### ISSUE TITLE
 No matching version found for @llamaindex/openai@0.1.1

### ISSUE THREAD

**Issue by 9M6** [run-llama/LlamaIndexTS#1207]
I've been getting this issue recently, 

```
 ERR_PNPM_NO_MATCHING_VERSION  No matching version found for @llamaindex/openai@0.1.1

This error happened while installing the dependencies of llamaindex@0.5.27

The latest release of @llamaindex/openai is "0.1.2".

If you need the full list of all 1 published versions run "$ pnpm view @llamaindex/openai versions".
```

I'm not sure which package is importing llamaindex but seems the 0.1.1 doesnt exist in npmjs anymore.

**Comment by CahidArda** [comment]
We had the same error in our package where we use llamaindex 0.5.20. It requires @llamaindex/openai 0.1.1. We were unable to install the package after the version 0.1.1 was removed from npm. 

bumping llamaindex 0.6.0 fixed the issue since it depends on @llamaindex/openai 0.1.2. https://github.com/upstash/rag-chat/pull/72

Still, the older versions of @llamaindex/openai shouldn't have been removed from npm

**Comment by marcusschiesser** [comment]
@CahidArda sorry for the trouble, the version wasn't removed - the problem was that it was never published as it was accidentally marked as private package 😄
